export const ROUTES = {
  HOME: "/",
  LOGIN: "/employer/login",
  POST_JOB: "/post-job",
  postJobEdit: (jobId: string) => `/post-job/${jobId}`,
  POST_JOB_SUCCESS: "/post-job/success",
  FIND_JOBS: "/jobs",
  jobPublic: (publicJobId: string) => `/jobs/${publicJobId}`,
  EMPLOYER_REGISTER: "/employer/register",
  EMPLOYER_LOGIN: "/employer/login",
  EMPLOYER_DASHBOARD: "/employer/dashboard",
  EMPLOYER_JOBS: "/employer/jobs",
  EMPLOYER_CANDIDATES: "/employer/candidates",
  EMPLOYER_INTERVIEWS: "/employer/interviews",
  EMPLOYER_MESSAGES: "/employer/messages",
  EMPLOYER_SAVED_CANDIDATES: "/employer/saved-candidates",
  EMPLOYER_CAMPAIGNS: "/employer/campaigns",
  EMPLOYER_ANALYTICS: "/employer/analytics",
  EMPLOYER_REPORTS: "/employer/reports",
  EMPLOYER_SUBSCRIPTION: "/employer/subscription",
  EMPLOYER_COMPANY_PROFILE: "/employer/company-profile",
  EMPLOYER_TEAM_MANAGEMENT: "/employer/team-management",
  EMPLOYER_SETTINGS: "/employer/settings",
  EMPLOYER_HELP_CENTER: "/employer/help-center",
  JOB_SEEKER_REGISTER: "/job-seeker/register",
  JOB_SEEKER_LOGIN: "/job-seeker/login",
  JOB_SEEKER_DASHBOARD: "/job-seeker/dashboard",
  CONTACT: "/contact",
  EMPLOYERS: "/employer/register",
  JOB_CATEGORIES: "/job-categories",
  RESOURCES: "/resources",
  FAQS: "/faqs",
  HELP_CENTER: "/help-center",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  PRIVACY_POLICY: "/privacy-policy",
  GUIDELINES: "/guidelines",
} as const;
