export const ROUTES = {
  HOME: "/",
  LOGIN: "/employer/login",
  POST_JOB: "/post-job",
  EMPLOYER_REGISTER: "/employer/register",
  EMPLOYER_LOGIN: "/employer/login",
  EMPLOYER_DASHBOARD: "/employer/dashboard",
  JOB_SEEKER_REGISTER: "/job-seeker/register",
  JOB_SEEKER_LOGIN: "/job-seeker/login",
  JOB_SEEKER_DASHBOARD: "/job-seeker/dashboard",
  CONTACT: "/contact",
  FIND_JOBS: "/jobs",
  EMPLOYERS: "/employer/register",
  JOB_CATEGORIES: "/job-categories",
  RESOURCES: "/resources",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  PRIVACY_POLICY: "/privacy-policy",
  GUIDELINES: "/guidelines",
} as const;
